services:
  client:
    build:
      context: ./client
    ports:
      - "8080:80"
    depends_on:
      - server

  server:
    build:
      context: ./server
    environment:
      - POSTGRES_URL="postgres://user:*w$3eJkyN2^ygY!*@db:5432"
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "*w$3eJkyN2^ygY!*"
    ports:
      - "5432:5432"
    volumes:
      - ./data/psql:/var/lib/postgresql/data

